In [1]:
pip install ipykernel

Requirement already satisfied: ipykernel in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (7.2.0)
Requirement already satisfied: appnope>=0.1.2 in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from ipykernel) (0.1.4)
Requirement already satisfied: comm>=0.1.1 in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from ipykernel) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from ipykernel) (1.8.20)
Requirement already satisfied: ipython>=7.23.1 in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from ipykernel) (8.39.0)
Requirement already satisfied: jupyter-client>=8.8.0 in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from ipykernel) (8.8.0)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from ipykernel) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from ipykernel) (0.2.1)
Requirement already satisfied: nest-asyncio>=1.4 in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from ipykernel) (1.6.0)
Requirement already satisfied: packaging>=22 in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from ipykernel) (26.2)
Requirement already satisfied: psutil>=5.7 in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from ipykernel) (7.2.2)
Requirement already satisfied: pyzmq>=25 in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from ipykernel) (27.1.0)
Requirement already satisfied: tornado>=6.4.1 in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from ipykernel) (6.5.5)
Requirement already satisfied: traitlets>=5.4.0 in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from ipykernel) (5.15.0)
Requirement already satisfied: decorator in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel) (5.2.1)
Requirement already satisfied: exceptiongroup in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel) (1.3.1)
Requirement already satisfied: jedi>=0.16 in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel) (0.20.0)
Requirement already satisfied: pexpect>4.3 in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel) (2.20.0)
Requirement already satisfied: stack_data in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)
Requirement already satisfied: typing_extensions>=4.6 in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel) (4.15.0)
Requirement already satisfied: wcwidth in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.7.0)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel) (0.8.7)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from jupyter-client>=8.8.0->ipykernel) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel) (4.9.6)
Requirement already satisfied: ptyprocess>=0.5 in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel) (0.7.0)
Requirement already satisfied: six>=1.5 in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from python-dateutil>=2.8.2->jupyter-client>=8.8.0->ipykernel) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from stack_data->ipython>=7.23.1->ipykernel) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from stack_data->ipython>=7.23.1->ipykernel) (3.0.1)
Requirement already satisfied: pure-eval in /Users/sanchaybharara/Coding/tf310/lib/python3.10/site-packages (from stack_data->ipython>=7.23.1->ipykernel) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [3]:
data=pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
## preprocessing the data drop irrelevatn feature
data=data.drop(['RowNumber','CustomerId','CustomerId'], axis=1)
data.head()

,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [9]:
## encoder categorical variables

label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data.head()

,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,Hargrave,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,Hill,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,Onio,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,Boni,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,Mitchell,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [14]:
### changin the geopgraphy using one hot encoder as there are 3 4 geopgrphy only
from sklearn.preprocessing import OneHotEncoder
one_hot_encod_geo=OneHotEncoder()

geo_encoding=one_hot_encod_geo.fit_transform(data[['Geography']])
geo_encoding

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [15]:
one_hot_encod_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [16]:
geo_encode_df=pd.DataFrame(geo_encoding.toarray(), columns=one_hot_encod_geo.get_feature_names_out(['Geography']))
geo_encode_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [17]:
data=pd.concat([data.drop('Geography', axis=1),geo_encode_df], axis=1)
data.head()

,Surname,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,Hargrave,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,Hill,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,Onio,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,Boni,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,Mitchell,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [18]:
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('one_hot_encod_geo.pkl','wb') as file:
    pickle.dump(one_hot_encod_geo,file)

In [23]:
x = data.drop('Exited', axis=1)
y = data['Exited']

# Convert categorical columns to numeric
x = pd.get_dummies(x, drop_first=True)

# Split the data
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

# Scale features
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [24]:
x_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ..., -0.01118104,
        -0.01118104,  0.        ],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.01118104,
        -0.01118104,  0.        ],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.01118104,
        -0.01118104,  0.        ],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ..., -0.01118104,
        -0.01118104,  0.        ],
       [ 0.15932282,  0.91324755,  0.3900109 , ..., -0.01118104,
        -0.01118104,  0.        ],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.01118104,
        -0.01118104,  0.        ]])

In [28]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [30]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime